trigger: 
- master

name: $(SourceBranchName)-$(BuildID)-$(Rev:r)_$(Date:yyyy-MM-dd)

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: AwsCredentials
- name: DYNAMIC_ENV_NAME
  value: dynamic-env-$(Build.BuildID)
- name: ARTIFACT_NAME
  value: terraform-variables.txt
- name: ARTIFACT_PATH
  value: $(System.ArtifactsDirectory)/$(ARTIFACT_NAME)

stages:
- template: stages-dynamic-env.yml
