trigger: 
- master

name: $(SourceBranchName)-$(BuildID)-$(Rev:r)_$(Date:yyyy-MM-dd)

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: AwsCredentials
- name: DYNAMIC_ENV_NAME
  value: dynamic-env-$(Build.BuildID)

stages:
- template: stages-dynamic-env.yml
