trigger: none

name: $(SourceBranchName)-$(BuildID)-$(Rev:r)_$(Date:yyyy-MM-dd)

stages:
- stage: SeleniumTests
  displayName: Selenium Tests
  jobs:
  - job: TestWebsiteSelenium
    displayName: Test App website with Selenium

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: Install Node

    - script: |
        npm install
      displayName: Restore npm modules
      workingDirectory: ui-tests/selenium

    - script: |
        npm run lint
      displayName: Lint JavaScript
      workingDirectory: ui-tests/selenium

    - script: |
        npm test
      displayName: Run WebdriverIO Tests
      workingDirectory: ui-tests/selenium
      env:
        HEADLESS_CHROME: "true"

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      displayName: Publish test results
      inputs:
        testRunTitle: Selenium Tets Results
        testResultsFormat: JUnit
        testResultsFiles: ui-tests/selenium/test-results/*.xml

    - task: PublishBuildArtifacts@1
      condition: succeededOrFailed()
      displayName: Publish Selenium results artifact
      inputs:
        pathToPublish: ui-tests/selenium/test-results/*.xml
        ArtifactName: selenium-results-artifact-$(Build.BuildNumber)

    - task: PublishBuildArtifacts@1
      condition: succeededOrFailed()
      displayName: Publish Selenium output artifact
      inputs:
        pathToPublish: ui-tests/selenium-output/*
        ArtifactName: selenium-output-artifact-$(Build.BuildNumber)    