trigger: 
- master

name: $(SourceBranchName)-$(BuildID)-$(Rev:r)_$(Date:yyyy-MM-dd)

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: AwsCredentials
- name: DYNAMIC_ENV_NAME
  value: dynamic-env-$(Build.BuildID)
- name: TF_ARTIFACT_NAME
  value: terraform-variables-$(Build.BuildID)
- name: TF_OUTPUT_VARS
  value: variables.txt
- name: TF_ARTIFACT_PATH
  value: $(System.ArtifactsDirectory)/$(TF_ARTIFACT_NAME)
- name: LAMBDA_NODE_DEPLOY_ARTIFACT
  value: lambda-node-deploy-artifact-$(Build.BuildNumber)

stages:
- template: stages-dynamic-env.yml
