# trigger: 
# - master

# Disabled for now
trigger: none

name: $(SourceBranchName)-$(BuildID)-$(Rev:r)_$(Date:yyyy-MM-dd)

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: AwsCredentials

- name: ENVIRONMENT_NAME
  value: dynamic-env-$(Build.BuildID)

- name: TEST_RESULTS_PATH
  value: test-results/junit.xml
  
- name: TF_ARTIFACT_NAME
  value: terraform-variables-$(Build.BuildNumber)
- name: TF_OUTPUT_VARS
  value: variables.txt
- name: TF_ARTIFACT_PATH
  value: $(System.ArtifactsDirectory)/$(TF_ARTIFACT_NAME)

- name: LAMBDA_NODE_DEPLOY_ARTIFACT_NAME
  value: lambda-node-deploy-artifact-$(Build.BuildNumber)
- name: LAMBDA_NODE_FUNCTIONS_ZIP
  value: lambda-node-functions.zip
- name: LAMBDA_NODE_DEPLOY_ARTIFACT_PATH
  value: $(System.ArtifactsDirectory)/$(LAMBDA_NODE_DEPLOY_ARTIFACT_NAME)

stages:
- template: stages-dynamic-env.yml
