jobs:
- job: TestCypress
  displayName: Test Website with Cypress

  variables:
  - name: UI_TESTS_PATH
    value: $(Build.SourcesDirectory)/ui-tests/cypress-tests
  - name: CYPRESS_TEST_RESULTS_ARTIFACT
    value: cypress-test-results-$(Build.BuildNumber)

  steps:
  - template: step-install-node.yml

  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: $(TF_ARTIFACT_NAME)
    displayName: Download Terraform output artifact

  - script: npm install
    workingDirectory: $(UI_TESTS_PATH)
    displayName: Restore npm modules

  # TODO: run tests and collect results
  