jobs:
- job: BuildPythonFunctions
  displayName: Build Python Functions

  variables:
  - name: PYTHON_CODE_PATH
    value: $(Build.SourcesDirectory)/lambda-src/python

  steps:  
  - script: sh create-python-lambda-artifact.sh $(LAMBDA_PYTHON_FUNCTIONS_ZIP)
    workingDirectory: $(PYTHON_CODE_PATH)
    displayName: Create $(LAMBDA_PYTHON_FUNCTIONS_ZIP) artifact

  - task: PublishBuildArtifacts@1
    displayName: Publish $(LAMBDA_PYTHON_DEPLOY_ARTIFACT_NAME) artifact
    inputs:
      pathToPublish: $(PYTHON_CODE_PATH)/$(LAMBDA_PYTHON_FUNCTIONS_ZIP)
      ArtifactName: $(LAMBDA_PYTHON_DEPLOY_ARTIFACT_NAME)