jobs:
- job: DeployWebsite
  displayName: Deploy Website
  steps:  
  - template: step-install-aws-cli.yml

  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: $(TF_ARTIFACT_NAME)
    displayName: Download Terraform output artifact

  - script: |
      source $(TF_ARTIFACT_PATH)/$(TF_OUTPUT_VARS)
      echo "Updating $WEBSITE_URL website..."
      sh unix-scripts/deploy-website.sh $WEBSITE_BUCKET_NAME $API_URL $(ENVIRONMENT_NAME)
    displayName: Upload static website files to S3 bucket
    env: 
      AWS_ACCESS_KEY_ID: $(aws_access_key_id)
      AWS_SECRET_ACCESS_KEY: $(aws_secret_access_key)
      AWS_DEFAULT_REGION: $(region)