jobs:
- job: TestCypress
  displayName: Test Website with Cypress

  variables:
  - name: UI_TESTS_PATH
    value: $(Build.SourcesDirectory)/ui-tests/cypress-tests
  - name: SELENIUM_TEST_RESULTS_ARTIFACT
    value: cypress-test-results-$(Build.BuildNumber)

  steps:
  - template: step-install-node.yml

  # TODO: research and run tests here
  