jobs:
- job: TestCypress
  displayName: Test Website with Cypress

  variables:
  - name: UI_TESTS_PATH
    value: $(Build.SourcesDirectory)/ui-tests/cypress-tests
  - name: CYPRESS_TEST_RESULTS_ARTIFACT
    value: cypress-test-results-$(Build.BuildNumber)

  steps:
  - template: step-install-node.yml

  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: $(TF_ARTIFACT_NAME)
    displayName: Download Terraform output artifact

  - script: npm install
    workingDirectory: $(UI_TESTS_PATH)
    displayName: Restore npm modules

  - script: |  
      source $(TF_ARTIFACT_PATH)/$(TF_OUTPUT_VARS)
      echo '{"WEBSITE_URL":"${WEBSITE_URL}"}' > cypress.env.json
      npm test
    workingDirectory: $(UI_TESTS_PATH)
    displayName: Run Cypress tests

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunTitle: Cypress Tets Results
      testResultsFormat: JUnit
      testResultsFiles: $(UI_TESTS_PATH)/test-results/*.xml
    displayName: Publish test results

  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    inputs:
      pathToPublish: $(UI_TESTS_PATH)/test-results
      ArtifactName: $(CYPRESS_TEST_RESULTS_ARTIFACT)
    displayName: Publish $(CYPRESS_TEST_RESULTS_ARTIFACT) artifact

  # TODO: record screenshot and video artifacts
  