jobs:
- job: TestSelenium
  displayName: Test Website with Selenium

  variables:
  - name: UI_TESTS_PATH
    value: $(Build.SourcesDirectory)/ui-tests/selenium-tests
  - name: SELENIUM_TEST_RESULTS_ARTIFACT
    value: selenium-test-results-$(Build.BuildNumber)
  - name: SELENIUM_OUTPUT_ARTIFACT
    value: selenium-output-$(Build.BuildNumber)

  steps:
  - template: step-install-node.yml

  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: $(TF_ARTIFACT_NAME)
    displayName: Download Terraform output artifact

  - script: npm install
    workingDirectory: $(UI_TESTS_PATH)
    displayName: Restore npm modules

  - script: npm run lint
    workingDirectory: $(UI_TESTS_PATH)
    displayName: Lint JavaScript

  - script: |  
      cp $(TF_ARTIFACT_PATH)/$(TF_OUTPUT_VARS) ${DOTENV_FILE}
      npm test
    workingDirectory: $(UI_TESTS_PATH)
    env:
      HEADLESS_CHROME: "true"
    displayName: Run Selenium tests

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunTitle: Selenium Tets Results
      testResultsFormat: JUnit
      testResultsFiles: $(UI_TESTS_PATH)/test-results/*.xml
    displayName: Publish test results

  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    inputs:
      pathToPublish: $(UI_TESTS_PATH)/test-results
      ArtifactName: $(SELENIUM_TEST_RESULTS_ARTIFACT)
    displayName: Publish $(SELENIUM_TEST_RESULTS_ARTIFACT) artifact

  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    inputs:
      pathToPublish: $(UI_TESTS_PATH)/selenium-output
      ArtifactName: $(SELENIUM_OUTPUT_ARTIFACT)  
    displayName: Publish $(SELENIUM_OUTPUT_ARTIFACT) artifact