jobs:
- job: TestApiPostman
  displayName: Test App API with Postman

  variables:
  - name: TEST_RESULTS
    value: $(Build.SourcesDirectory)/api-tests/test-results/junit.xml

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: Install Node

  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: $(TF_ARTIFACT_NAME)
    displayName: Download Terraform output artifact
  
  # Copy the saved Terraform output variables as a local ".env" file, install Newman, update the Postman environment file and run the collection
  - script: |
      cp $(TF_ARTIFACT_PATH)/$(TF_OUTPUT_VARS) .env
      npm install
      npm start
      sh run-newman-tests.sh $(TEST_RESULTS)
    displayName: Run Postman colleciton using Newman
    workingDirectory: api-tests
      
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    displayName: Publish Postman test results
    inputs:
      testRunTitle: Postman Results
      testResultsFormat: JUnit
      testResultsFiles: $(TEST_RESULTS)
      failTaskOnFailedTests: false

  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    displayName: Publish [postman-results-$(Build.BuildNumber)] artifact
    inputs:
      pathToPublish: $(TEST_RESULTS)
      ArtifactName: postman-results-$(Build.BuildNumber)