jobs:
- job: TestApiPostman
  displayName: Test App API with Postman

  variables:
  - name: API_TESTS_PATH
    value: $(Build.SourcesDirectory)/api-tests
  - name: TEST_RESULTS
    value: $(API_TESTS_PATH)/$(TEST_RESULTS_PATH)
  - name: POSTMAN_TEST_RESULTS_ARTIFACT
    value: postman-results-$(Build.BuildNumber)

  steps:
  - template: step-install-node.yml

  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: $(TF_ARTIFACT_NAME)
    displayName: Download Terraform output artifact
  
  # Copy the saved Terraform output variables as a local ".env" file, install Newman, update the Postman environment file and run the collection
  - script: |
      cp $(TF_ARTIFACT_PATH)/$(TF_OUTPUT_VARS) .env
      npm install
      npm start
    displayName: Setup Newman environment file
    workingDirectory: $(API_TESTS_PATH)

  - script: sh run-newman-tests.sh $(TEST_RESULTS)
    displayName: Run Postman colleciton using Newman
    workingDirectory: $(API_TESTS_PATH)

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    displayName: Publish Postman test results
    inputs:
      testRunTitle: Postman Results
      testResultsFormat: JUnit
      testResultsFiles: $(TEST_RESULTS)

  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    displayName: Publish $(POSTMAN_TEST_RESULTS_ARTIFACT) artifact
    inputs:
      pathToPublish: $(TEST_RESULTS)
      ArtifactName: $(POSTMAN_TEST_RESULTS_ARTIFACT)