jobs:
- job: TerraformDestroy
  displayName: Terraform Destroy
  steps:
  - template: steps-setup-terraform.yml

  - script: |    
      sh tf-destroy.sh $(ENVIRONMENT_NAME) ${TF_BACKEND_CONFIG_NAME}
      
      if [[ $? != 0 ]]; then exit 1; fi
      
      sh tf-delete-workspace.sh $(ENVIRONMENT_NAME)
    displayName: Destroy $(ENVIRONMENT_NAME) environment
    workingDirectory: terraform
    env: 
      AWS_ACCESS_KEY_ID: $(aws_access_key_id)
      AWS_SECRET_ACCESS_KEY: $(aws_secret_access_key)
      AWS_DEFAULT_REGION: $(region)     

    