jobs:
- job: TestWebsiteSelenium
  displayName: Test App with Selenium

  variables:
  - name: UI_TESTS_PATH
    value: $(Build.SourcesDirectory)/ui-tests/selenium-tests
  - name: SELENIUM_TEST_RESULTS_ARTIFACT
    value: selenium-test-results-$(Build.BuildNumber)
  - name: SELENIUM_OUTPUT_ARTIFACT
    value: selenium-output-$(Build.BuildNumber)

  steps:
  - template: step-install-node.yml

  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: $(TF_ARTIFACT_NAME)
    displayName: Download Terraform output artifact

  - script: npm install
    displayName: Restore npm modules
    workingDirectory: $(UI_TESTS_PATH)

  - script: npm run lint
    displayName: Lint JavaScript
    workingDirectory: $(UI_TESTS_PATH)

  - script: |  
      cp $(TF_ARTIFACT_PATH)/$(TF_OUTPUT_VARS) .env
      npm test
    displayName: Run Selenium tests
    workingDirectory: $(UI_TESTS_PATH)
    env:
      HEADLESS_CHROME: "true"

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    displayName: Publish test results
    inputs:
      testRunTitle: Selenium Tets Results
      testResultsFormat: JUnit
      testResultsFiles: $(UI_TESTS_PATH)/test-results/*.xml

  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    displayName: Publish $(SELENIUM_TEST_RESULTS_ARTIFACT) artifact
    inputs:
      pathToPublish: $(UI_TESTS_PATH)/test-results
      ArtifactName: $(SELENIUM_TEST_RESULTS_ARTIFACT)

  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    displayName: Publish $(SELENIUM_OUTPUT_ARTIFACT) artifact
    inputs:
      pathToPublish: $(UI_TESTS_PATH)/selenium-output
      ArtifactName: $(SELENIUM_OUTPUT_ARTIFACT)  