jobs:
- job: TerraformApply
  displayName: Terraform Apply

  steps:
  - template: steps-setup-terraform.yml

  - script: |    
      sh tf-apply.sh $(ENVIRONMENT_NAME) ${TF_BACKEND_CONFIG_NAME} $(DOTENV_FILE)
      mkdir -p $(TF_ARTIFACT_PATH)
      cp $(DOTENV_FILE) $(TF_ARTIFACT_PATH)/$(TF_OUTPUT_VARS)
    displayName: Create $(ENVIRONMENT_NAME) environment
    workingDirectory: terraform
    env: 
      AWS_ACCESS_KEY_ID: $(aws_access_key_id)
      AWS_SECRET_ACCESS_KEY: $(aws_secret_access_key)
      AWS_DEFAULT_REGION: $(region)   

  - task: PublishBuildArtifacts@1
    displayName: Publish $(TF_ARTIFACT_NAME)
    inputs:
      pathToPublish: $(TF_ARTIFACT_PATH)
      ArtifactName: $(TF_ARTIFACT_NAME)
