jobs:
- job: TestPostman
  displayName: Test API with Postman

  variables:
  - name: API_TESTS_PATH
    value: $(Build.SourcesDirectory)/api-tests
  - name: TEST_RESULTS
    value: $(API_TESTS_PATH)/$(TEST_RESULTS_PATH)
  - name: POSTMAN_TEST_RESULTS_ARTIFACT
    value: postman-test-results-$(Build.BuildNumber)

  steps:
  - template: step-install-node.yml

  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: $(TF_ARTIFACT_NAME)
    displayName: Download Terraform output artifact
  
  - script: |
      cp $(TF_ARTIFACT_PATH)/$(TF_OUTPUT_VARS) ${DOTENV_FILE}
      npm install
      npm run build-env-file
    workingDirectory: $(API_TESTS_PATH)
    displayName: Setup Postman environment file

  - script: |
      sh run-newman-tests.sh $(TEST_RESULTS)
      
      if [[ $? != 0 ]]; then exit 1; fi
    displayName: Run Postman colleciton using Newman
    workingDirectory: $(API_TESTS_PATH)

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunTitle: Postman Results
      testResultsFormat: JUnit
      testResultsFiles: $(TEST_RESULTS)
    displayName: Publish Postman test results

  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    inputs:
      pathToPublish: $(TEST_RESULTS)
      ArtifactName: $(POSTMAN_TEST_RESULTS_ARTIFACT)
    displayName: Publish $(POSTMAN_TEST_RESULTS_ARTIFACT) artifact
    