jobs:
- job: DeployLambdaNodeFunctions
  displayName: Deploy Lambda Node Functions

  variables:
  - name: LAMBDA_NODE_FUNCTIONS_ZIP_PATH
    value: $(LAMBDA_NODE_DEPLOY_ARTIFACT_PATH)/$(LAMBDA_NODE_FUNCTIONS_ZIP)

  steps:  
  - template: step-install-aws-cli.yml

  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: $(TF_ARTIFACT_NAME)
    displayName: Download Terraform output artifact

  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: $(LAMBDA_NODE_DEPLOY_ARTIFACT_NAME)
    displayName: Download Node functions artifact

  - script: |
      source $(TF_ARTIFACT_PATH)/$(TF_OUTPUT_VARS)

      sh upload-lambda-artifact.sh $(LAMBDA_NODE_FUNCTIONS_ZIP_PATH) $DEPLOYMENT_BUCKET_NAME $(LAMBDA_NODE_FUNCTIONS_ZIP)
      sh deploy-lambda-artifact.sh $LAMBDA_NODE_HELLO_NAME $DEPLOYMENT_BUCKET_NAME $(LAMBDA_NODE_FUNCTIONS_ZIP)

# "TOOD: run the above call for all node lambda functions"
    displayName: Update Node Lambda functions
    workingDirectory: unix-scripts
    env: 
      AWS_ACCESS_KEY_ID: $(aws_access_key_id)
      AWS_SECRET_ACCESS_KEY: $(aws_secret_access_key)
      AWS_DEFAULT_REGION: $(region)