jobs:
- job: DeployWebsite
  displayName: Deploy Website

  steps:
  - script: |
      echo "TODO: copy website static files to the S3 bucket"
    displayName: Upload static website files to S3 bucket

  - script: |
      echo "TODO: update the env.json to point to the right API Gateway URL"
    displayName: Update the env.json file

- job: DeployLambdaFunctions
  displayName: Deploy Lambda Functions

  steps:
  - script: |
      echo "TODO: npm install --production, zip files, upload to S3 bucket and deploy to Lambda"
    displayName: Deploy latest code to Lambda