jobs:
- job: TestWebsiteSelenium
  displayName: Test App website with Selenium
  steps:
  - script: |
      echo "TODO: run WebdriverIO"
    displayName: Run WebdriverIO Tests

- job: TestWebsiteCypress
  displayName: Test App website with Cypress
  steps:
  - script: |
      echo "TODO: run Cypress"
    displayName: Run Cypress

- job: TestApiPostman
  displayName: Test App API with Postman
  steps:
  - script: |
      echo "TODO: run newman collection against the API"
    displayName: Run Postman colleciton using Newman