jobs:
- template: job-newman-tests.yml

# - job: TestWebsiteSelenium
#   displayName: Test App website with Selenium
#   steps:
#   - script: |
#       echo "TODO: run WebdriverIO"
#     displayName: Run WebdriverIO Tests

# - job: TestWebsiteCypress
#   displayName: Test App website with Cypress
#   steps:
#   - script: |
#       echo "TODO: run Cypress"
#     displayName: Run Cypress