jobs:
- job: TerraformApply
  displayName: Terraform Apply

  steps:
  - template: steps-terraform-secure-files.yml

  - script: |    
      terraform init -backend-config="aws-s3-backend.tfconfig"
      terraform validate
      sh select-workspace.sh $(DYNAMIC_ENV_NAME)
      terraform plan -out $(DYNAMIC_ENV_NAME).tfplan
      terraform apply "$(DYNAMIC_ENV_NAME).tfplan"

      mkdir -p $(ARTIFACT_PATH)
      terraform output website_bucket_name > $(ARTIFACT_PATH)/website_bucket_name
      terraform output serverless_rest_api_base_url >> $(ARTIFACT_PATH)/serverless_rest_api_base_url
      terraform output website_url > $(ARTIFACT_PATH)/website_url
    displayName: Create $(DYNAMIC_ENV_NAME) environment
    workingDirectory: terraform
    env: 
      AWS_ACCESS_KEY_ID: $(aws_access_key_id)
      AWS_SECRET_ACCESS_KEY: $(aws_secret_access_key)
      AWS_DEFAULT_REGION: $(region)   

  - task: PublishBuildArtifacts@1
    displayName: Publish $(ARTIFACT_NAME)
    inputs:
      pathToPublish: $(ARTIFACT_PATH)
      ArtifactName: $(ARTIFACT_NAME)
