jobs:
- job: TerraformApply
  displayName: Terraform Apply
  steps:
  - template: steps-terraform-secure-files.yml

  - script: |    
      terraform init -backend-config="aws-s3-backend.tfconfig"
      terraform validate
      sh select-workspace.sh $(DYNAMIC_ENV_NAME)
      terraform plan -out $(DYNAMIC_ENV_NAME).tfplan
      terraform apply "$(DYNAMIC_ENV_NAME).tfplan"

      mkdir -p $(TF_ARTIFACT_PATH)

      echo WEBSITE_BUCKET_NAME=`terraform output website_bucket_name` > $(TF_ARTIFACT_PATH)/$(TF_OUTPUT_VARS)
      echo API_URL=`terraform output serverless_rest_api_base_url` >> $(TF_ARTIFACT_PATH)/$(TF_OUTPUT_VARS)
      echo WEBSITE_URL=`terraform output website_url` >> $(TF_ARTIFACT_PATH)/$(TF_OUTPUT_VARS)
      echo LAMBDA_NODE_HELLO_NAME=`terraform output lambda_node_hello_name` >> $(TF_ARTIFACT_PATH)/$(TF_OUTPUT_VARS)
      echo LAMBDA_PYTHON_HELLO_NAME=`terraform output lambda_python_hello_name` >> $(TF_ARTIFACT_PATH)/$(TF_OUTPUT_VARS)
      echo DEPLOYMENT_BUCKET_NAME=`terraform output deployment_bucket_name` >> $(TF_ARTIFACT_PATH)/$(TF_OUTPUT_VARS)
    displayName: Create $(DYNAMIC_ENV_NAME) environment
    workingDirectory: terraform
    env: 
      AWS_ACCESS_KEY_ID: $(aws_access_key_id)
      AWS_SECRET_ACCESS_KEY: $(aws_secret_access_key)
      AWS_DEFAULT_REGION: $(region)   

  - task: PublishBuildArtifacts@1
    displayName: Publish $(TF_ARTIFACT_NAME)
    inputs:
      pathToPublish: $(TF_ARTIFACT_PATH)
      ArtifactName: $(TF_ARTIFACT_NAME)
