jobs:
- job: TerraformDestroy
  displayName: Terraform Destroy

  steps:
  - template: steps-terraform-secure-files.yml

  - script: |    
      terraform init -backend-config="aws-s3-backend.tfconfig"
      sh select-workspace.sh $(DYNAMIC_ENV_NAME)
      terraform destroy -auto-approve
      terraform workspace select default
      terraform workspace delete $(DYNAMIC_ENV_NAME)
    displayName: Destroy $(DYNAMIC_ENV_NAME) environment
    workingDirectory: terraform
    env: 
      AWS_ACCESS_KEY_ID: $(aws_access_key_id)
      AWS_SECRET_ACCESS_KEY: $(aws_secret_access_key)
      AWS_DEFAULT_REGION: $(region)     