jobs:
- template: job-build-lambda-node-functions.yml

# - job: UnitTestPythonFunctions
#   displayName: Unit Test Python Functions
#   steps:
#   - script: |
#       echo "TODO: restore requirements and run unit tests"
#     displayName: Restore requirements and run unit tests