jobs:
- job: TerraformApply
  displayName: Terraform Apply

  steps:
  - task: DownloadSecureFile@1
    name: "tfconfig"
    displayName: 'Downlaod secure aws-s3-backend.tfconfig file'
    inputs:
      secureFile: aws-s3-backend.tfconfig

  - task: DownloadSecureFile@1
    name: "tfvars"
    displayName: 'Downlaod secure terraform.tfvars file'
    inputs:
      secureFile: terraform.tfvars

  - script: |
      cp $(tfconfig.secureFilePath) terraform/aws-s3-backend.tfconfig
      cp $(tfvars.secureFilePath) terraform/terraform.tfvars
    displayName: Copy secure files to terraform directory

  # Third-party task from the Marketplace
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
    displayName: Install Terraform
    inputs:
      terraformVersion: 0.12.25

  - script: |    
      terraform init -backend-config="aws-s3-backend.tfconfig"
      terraform validate
      sh select-workspace.sh $(DYNAMIC_ENV_NAME)
      terraform plan -out $(DYNAMIC_ENV_NAME).tfplan
      terraform apply "$(DYNAMIC_ENV_NAME).tfplan"
    displayName: Create $(DYNAMIC_ENV_NAME) environment
    workingDirectory: terraform
    env: 
      AWS_ACCESS_KEY_ID: $(aws_access_key_id)
      AWS_SECRET_ACCESS_KEY: $(aws_secret_access_key)
      AWS_DEFAULT_REGION: $(region)   