jobs:
- job: DeployWebsite
  displayName: Deploy Website
  steps:  
  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: $(ARTIFACT_NAME)

  - script: |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      aws --version
    displayName: Install AWS CLI 2

  - script: |
      source $(ARTIFACT_PATH)

      aws s3 cp website/ s3://$BUCKET_NAME/ --recursive --acl public-read
# BUCKET_NAME=$(cat $(System.ArtifactsDirectory)/$(ARTIFACT_NAME)/website_bucket_name)
# API_URL=$(cat $(System.ArtifactsDirectory)/$(ARTIFACT_NAME)/serverless_rest_api_base_url)
# WEBSITE_URL=$(cat $(System.ArtifactsDirectory)/$(ARTIFACT_NAME)/website_url)
    displayName: Upload static website files to S3 bucket
    env: 
      AWS_ACCESS_KEY_ID: $(aws_access_key_id)
      AWS_SECRET_ACCESS_KEY: $(aws_secret_access_key)
      AWS_DEFAULT_REGION: $(region)   

  - script: |
      echo "TODO: update the env.json to point to the right API Gateway URL"
    displayName: Update the env.json file

# - job: DeployLambdaFunctions
#   displayName: Deploy Lambda Functions
#   steps:
#   - script: |
#       echo "TODO: npm install --production, zip files, upload to S3 bucket and deploy to Lambda"
#     displayName: Deploy latest code to Lambda