# Typical CI pipeline that tests the application end-to-end
trigger: 
- master

# NOTE: only lowercase alphanumeric characters and hyphens allowed in S3 bucket name
name: $(SourceBranchName)-$(BuildID)-$(Rev:r)-$(Date:yyyy-MM-dd)

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: AwsCredentials
- name: ENVIRONMENT_NAME
  value: dynamic-$(Build.BuildNumber)
- name: TEST_RESULTS_PATH
  value: test-results/junit.xml
- name: DOTENV_FILE
  value: .env
- name: TF_BACKEND_CONFIG_NAME
  value: aws-s3-backend.tfconfig  
- name: TF_ARTIFACT_NAME
  value: terraform-variables-$(Build.BuildNumber)
- name: TF_OUTPUT_VARS
  value: variables.txt
- name: TF_ARTIFACT_PATH
  value: $(System.ArtifactsDirectory)/$(TF_ARTIFACT_NAME)

- name: LAMBDA_NODE_DEPLOY_ARTIFACT_NAME
  value: lambda-node-deploy-artifact-$(Build.BuildNumber)
- name: LAMBDA_NODE_FUNCTIONS_ZIP
  value: lambda-node-functions.zip
- name: LAMBDA_NODE_DEPLOY_ARTIFACT_PATH
  value: $(System.ArtifactsDirectory)/$(LAMBDA_NODE_DEPLOY_ARTIFACT_NAME)

- name: LAMBDA_PYTHON_DEPLOY_ARTIFACT_NAME
  value: lambda-python-deploy-artifact-$(Build.BuildNumber)
- name: LAMBDA_PYTHON_FUNCTIONS_ZIP
  value: lambda-python-functions.zip
- name: LAMBDA_PYTHON_DEPLOY_ARTIFACT_PATH
  value: $(System.ArtifactsDirectory)/$(LAMBDA_PYTHON_DEPLOY_ARTIFACT_NAME)

stages:
- template: stages-build-test-deploy.yml
- template: stages-destroy.yml
