trigger: none

name: $(SourceBranchName)-$(BuildID)-$(Rev:r)_$(Date:yyyy-MM-dd)

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Development

jobs:
- job: TestWebsiteSelenium
  displayName: Test App with Selenium

  steps:
  - template: step-install-node.yml

  - script: npm install
    displayName: Restore npm modules
    workingDirectory: ui-tests/selenium

  - script: npm run lint
    displayName: Lint JavaScript
    workingDirectory: ui-tests/selenium

  - script: npm test
    displayName: Run Selenium tests
    workingDirectory: ui-tests/selenium
    env:
      HEADLESS_CHROME: "true"
      WEBSITE_URL: $(website_url)

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    displayName: Publish test results
    inputs:
      testRunTitle: Selenium Tets Results
      testResultsFormat: JUnit
      testResultsFiles: ui-tests/selenium/test-results/*.xml

  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    displayName: Publish Selenium results artifact
    inputs:
      pathToPublish: ui-tests/selenium/test-results
      ArtifactName: selenium-test-results-artifact-$(Build.BuildNumber)

  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    displayName: Publish Selenium output artifact
    inputs:
      pathToPublish: ui-tests/selenium/selenium-output
      ArtifactName: selenium-output-artifact-$(Build.BuildNumber)    