stages:
- stage: BuildLambdaFunctions
  displayName: Build Lambda Functions
  jobs:
  - template: jobs-build-lambda-functions.yml

- stage: SetupAwsInfrastrcture
  displayName: Setup AWS Infrastrcture
  jobs:
  - template: job-build-aws-infrastructure.yml
      
- stage: DeployApp
  displayName: Deploy App
  jobs:
  - template: jobs-deploy-app.yml
      
- stage: TestApp
  displayName: Test App
  jobs:
  - template: jobs-test-app.yml

- stage: AwsCleanup
  displayName: AWS Cleanup
  # The pipeline has moved on beyond BuildLambdaFunctions so potentially AWS infrastructure has been built
  condition: succeeded("BuildLambdaFunctions")
  jobs:
  - template: job-destroy-aws-infrastructure.yml