stages:
- stage: BuildApp
  displayName: Build App
  jobs:
  - template: jobs-build-app.yml

- stage: AwsSetup
  displayName: AWS Setup
  jobs:
  - template: job-aws-setup.yml
      
- stage: DeployApp
  displayName: Deploy App
  jobs:
  - template: jobs-deploy-app.yml
      
- stage: TestApp
  displayName: Test App
  jobs:
  - template: jobs-test-app.yml